using OumezzineAcademy.Application.Abstractions;
using OumezzineAcademy.Domain.Catalog;
using OumezzineAcademy.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace OumezzineAcademy.Infrastructure.Persistence;

public sealed class EfAdminLessonQueries(ApplicationDbContext db) : IAdminLessonQueries
{
    public async Task<(AdminLessonContextDto Context,IReadOnlyList<AdminLessonListDto> Lessons)?> ListAsync(Guid courseId,Guid chapterId,CancellationToken t=default){var c=await db.StudyCourseContents.AsNoTracking().Where(x=>x.Id==chapterId&&x.CourseId==courseId).Select(x=>new AdminLessonContextDto(courseId,chapterId,x.Order,x.Course.Translations.Where(t=>t.LanguageCode=="fr").Select(t=>t.Title).FirstOrDefault()??x.Course.Title,x.Translations.Where(t=>t.LanguageCode=="fr").Select(t=>t.Title).FirstOrDefault()??x.Title,x.Translations.Where(t=>t.LanguageCode=="fr").Select(t=>(StudyStatus?)t.PublicationStatus).FirstOrDefault(),x.Translations.Where(t=>t.LanguageCode=="en").Select(t=>(StudyStatus?)t.PublicationStatus).FirstOrDefault())).FirstOrDefaultAsync(t);if(c is null)return null;var l=await db.StudyCourseLessons.AsNoTracking().Where(x=>x.CourseContentId==chapterId).OrderBy(x=>x.Order).ThenBy(x=>x.Id).Select(x=>new AdminLessonListDto(x.Id,x.Order,x.DurationMinutes,x.Translations.Where(t=>t.LanguageCode=="fr").Select(t=>t.Slug).FirstOrDefault()??x.Slug,x.LastModifiedOnUtc,x.Translations.Where(t=>t.LanguageCode=="fr").Select(t=>t.Title).FirstOrDefault()??x.Title,x.Translations.Where(t=>t.LanguageCode=="en").Select(t=>t.Title).FirstOrDefault()??"Missing",x.Translations.Where(t=>t.LanguageCode=="fr").Select(t=>(StudyStatus?)t.PublicationStatus).FirstOrDefault(),x.Translations.Where(t=>t.LanguageCode=="en").Select(t=>(StudyStatus?)t.PublicationStatus).FirstOrDefault(),x.Translations.Any(t=>t.ContentHtml!=null&&t.ContentHtml!=""),x.Translations.Any(t=>t.VideoUrl!=null&&t.VideoUrl!=""),x.Translations.Any(t=>t.DocumentUrl!=null&&t.DocumentUrl!=""))).ToListAsync(t);return(c,l);}
    public async Task<AdminLessonEditDto?> GetForEditAsync(Guid courseId,Guid chapterId,Guid? lessonId,CancellationToken t=default){var c=await db.StudyCourseContents.AsNoTracking().Include(x=>x.Course).ThenInclude(x=>x.Translations).Include(x=>x.Translations).FirstOrDefaultAsync(x=>x.Id==chapterId&&x.CourseId==courseId,t);if(c is null)return null;var e=lessonId.HasValue?await db.StudyCourseLessons.AsNoTracking().Include(x=>x.Translations).FirstOrDefaultAsync(x=>x.Id==lessonId&&x.CourseContentId==chapterId,t):null;AdminLessonTranslationDto M(string l){var x=e?.Translations.FirstOrDefault(x=>x.LanguageCode==l);return new(x?.Title,x?.Slug,x?.Summary,x?.ContentHtml,x?.VideoUrl,x?.DocumentUrl,x?.MetaTitle,x?.MetaDescription,x?.PublicationStatus??StudyStatus.Draft);}return new(e?.Id??Guid.Empty,courseId,chapterId,e?.Order??(await db.StudyCourseLessons.CountAsync(x=>x.CourseContentId==chapterId,t)+1),e?.DurationMinutes,c.Course.Translations.FirstOrDefault(x=>x.LanguageCode=="fr")?.Title??c.Course.Title,c.Course.Translations.FirstOrDefault(x=>x.LanguageCode=="en")?.Title??"Missing",c.Translations.FirstOrDefault(x=>x.LanguageCode=="fr")?.Title??c.Title,M("fr"),M("en"));}
    public Task<bool> SlugExistsAsync(string l,string s,Guid id,CancellationToken t=default)=>db.StudyCourseLessonTranslations.AnyAsync(x=>x.LanguageCode==l&&x.Slug==s&&x.CourseLessonId!=id,t);
}

public sealed class EfAdminLessonCoreCommands(ApplicationDbContext db,IHtmlSanitizer sanitizer) : IAdminLessonCoreCommands
{
    public async Task<(bool Success,Guid LessonId,string? Error)> SaveAsync(AdminLessonSaveCommand m,CancellationToken t=default){var chapter=await db.StudyCourseContents.FirstOrDefaultAsync(x=>x.Id==m.ChapterId&&x.CourseId==m.CourseId,t);if(chapter is null)return(false,Guid.Empty,"Chapter not found.");var isNew=!m.Id.HasValue||m.Id.Value==Guid.Empty;var e=isNew?new CourseLesson{Id=Guid.NewGuid(),CourseContentId=m.ChapterId,CreatedOnUtc=DateTime.UtcNow}:await db.StudyCourseLessons.Include(x=>x.Translations).FirstOrDefaultAsync(x=>x.Id==m.Id&&x.CourseContentId==m.ChapterId,t);if(e is null)return(false,Guid.Empty,"Lesson not found.");e.Order=Math.Max(1,m.Order);e.DurationMinutes=m.DurationMinutes;e.Title=m.French.Title??m.English.Title??"Lesson";e.Slug=m.French.Slug??m.English.Slug??$"lesson-{e.Id:N}";e.Summary=m.French.Summary;e.Description=m.French.ContentHtml;e.VideoUrl=m.French.VideoUrl;e.DocumentUrl=m.French.DocumentUrl;e.Status=m.French.PublicationStatus;db.Entry(e).Property<bool>("IsDeleted").CurrentValue=false;Upsert(e,"fr",m.French);Upsert(e,"en",m.English);if(isNew)db.StudyCourseLessons.Add(e);await NormalizeAsync(m.ChapterId,isNew?e:null,null,t);await db.SaveChangesAsync(t);return(true,e.Id,null);}
    public async Task MoveAsync(Guid courseId,Guid chapterId,Guid lessonId,int direction,CancellationToken t=default){var a=await db.StudyCourseLessons.Where(x=>x.CourseContentId==chapterId&&x.CourseContent.CourseId==courseId).OrderBy(x=>x.Order).ThenBy(x=>x.Id).ToListAsync(t);var i=a.FindIndex(x=>x.Id==lessonId);var j=i+direction;if(i<0||j<0||j>=a.Count)return;(a[i].Order,a[j].Order)=(a[j].Order,a[i].Order);await NormalizeAsync(chapterId,null,null,t);await db.SaveChangesAsync(t);}
    private void Upsert(CourseLesson e,string l,AdminLessonTranslationDto i){if(string.IsNullOrWhiteSpace(i.Title)&&string.IsNullOrWhiteSpace(i.Slug)&&string.IsNullOrWhiteSpace(i.ContentHtml))return;var x=e.Translations.FirstOrDefault(x=>x.LanguageCode==l);if(x is null){x=new CourseLessonTranslation{Id=Guid.NewGuid(),CourseLessonId=e.Id};e.Translations.Add(x);}x.LanguageCode=l;x.Title=i.Title?.Trim()??"";x.Slug=i.Slug?.Trim()??"";x.Summary=i.Summary;x.ContentHtml=sanitizer.Sanitize(i.ContentHtml);x.VideoUrl=i.VideoUrl;x.DocumentUrl=i.DocumentUrl;x.MetaTitle=i.MetaTitle;x.MetaDescription=i.MetaDescription;x.PublicationStatus=i.PublicationStatus;}
    private async Task NormalizeAsync(Guid id,CourseLesson? pending,Guid? excludedId,CancellationToken t){var a=await db.StudyCourseLessons.Where(x=>x.CourseContentId==id&&(!excludedId.HasValue||x.Id!=excludedId.Value)).OrderBy(x=>x.Order).ThenBy(x=>x.Id).ToListAsync(t);if(pending is not null&&!a.Any(x=>x.Id==pending.Id))a.Add(pending);a=a.OrderBy(x=>x.Order).ThenBy(x=>x.Id).ToList();for(var i=0;i<a.Count;i++)a[i].Order=i+1;}
}
