using Microsoft.EntityFrameworkCore;
using OumezzineAcademy.Application.Abstractions;
using OumezzineAcademy.Domain.Catalog;
using OumezzineAcademy.Infrastructure.Data;

namespace OumezzineAcademy.Infrastructure.Persistence;

public sealed class EfAdminLearningPathQueries(ApplicationDbContext db) : IAdminLearningPathQueries
{
    public async Task<IReadOnlyList<AdminLearningPathListDto>> ListAsync(CancellationToken t = default) => await db.StudyLearningPaths.AsNoTracking().OrderBy(x => x.Slug).Select(x => new AdminLearningPathListDto(x.Id, x.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.Translations.Where(t => t.LanguageCode == "en").Select(t => t.Title).FirstOrDefault() ?? "Parcours sans traduction", x.LearningPathCategory.Title, x.Level, x.Translations.Where(t => t.LanguageCode == "fr").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), x.Translations.Where(t => t.LanguageCode == "en").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), x.LearningPathCourses.Count)).ToListAsync(t);

    public async Task<AdminLearningPathEditDto?> GetForEditAsync(Guid? id, CancellationToken t = default)
    { var cats = await db.StudyLearningPathCategories.AsNoTracking().OrderBy(x => x.Title).Select(x => new AdminLearningPathCategoryOptionDto(x.Id, x.Title)).ToListAsync(t); var e = id.HasValue ? await db.StudyLearningPaths.AsNoTracking().Include(x => x.Translations).FirstOrDefaultAsync(x => x.Id == id, t) : null; AdminLearningPathTranslationDto M(string l) { var x = e?.Translations.FirstOrDefault(x => x.LanguageCode == l); return new(x?.Title, x?.Slug, x?.Summary, x?.MetaTitle, x?.MetaDescription, x?.PublicationStatus ?? StudyStatus.Draft); } return new(e?.Id ?? Guid.Empty, e?.LearningPathCategoryId ?? Guid.Empty, e?.Level ?? StudyLevel.Beginner, e?.Thumbnail, cats.FirstOrDefault(x => x.Id == (e?.LearningPathCategoryId ?? Guid.Empty))?.Title ?? "Catégorie", M("fr"), M("en"), cats); }

    public Task<bool> SlugExistsAsync(string l, string s, Guid id, CancellationToken t = default) => db.StudyLearningPathTranslations.AnyAsync(x => x.LanguageCode == l && x.Slug == s && x.LearningPathId != id, t);

    public async Task<AdminLearningPathCompositionDto?> GetCompositionAsync(Guid id, CancellationToken t = default)
    { var p = await db.StudyLearningPaths.AsNoTracking().Where(x => x.Id == id).Select(x => new { x.Id, Title = x.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.Title }).FirstOrDefaultAsync(t); if (p is null) return null; var selected = await db.StudyLearningPathCourses.AsNoTracking().Where(x => x.LearningPathId == id).OrderBy(x => x.Order).Select(x => new AdminLearningPathCourseOptionDto(x.Id, x.CourseId, x.Order, x.Course.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.Course.Title, x.Course.Slug, x.Course.Level, x.Course.CourseCategory.Title, x.Course.Translations.Where(t => t.LanguageCode == "fr").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), x.Course.Translations.Where(t => t.LanguageCode == "en").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), true)).ToListAsync(t); var ids = selected.Select(x => x.CourseId).ToHashSet(); var available = await db.StudyCourses.AsNoTracking().Where(x => !ids.Contains(x.Id)).OrderBy(x => x.Title).Select(x => new AdminLearningPathCourseOptionDto(Guid.Empty, x.Id, 0, x.Title, x.Slug, x.Level, x.CourseCategory.Title, x.Translations.Where(t => t.LanguageCode == "fr").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), x.Translations.Where(t => t.LanguageCode == "en").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), false)).ToListAsync(t); return new(p.Id, p.Title, selected, available); }
}

public sealed class EfAdminLearningPathCoreCommands(ApplicationDbContext db, IHtmlSanitizer sanitizer) : IAdminLearningPathCoreCommands
{
    public async Task<(bool Success, Guid LearningPathId, string? Error)> SaveAsync(AdminLearningPathSaveCommand m, CancellationToken t = default)
    { if (!await db.StudyLearningPathCategories.AnyAsync(x => x.Id == m.CategoryId, t)) return (false, Guid.Empty, "Category not found."); var e = m.Id.HasValue && m.Id.Value != Guid.Empty ? await db.StudyLearningPaths.Include(x => x.Translations).FirstOrDefaultAsync(x => x.Id == m.Id, t) : new LearningPath { Id = Guid.NewGuid(), CreatedOnUtc = DateTime.UtcNow }; if (e is null) return (false, Guid.Empty, "Learning path not found."); e.LearningPathCategoryId = m.CategoryId; e.Level = m.Level; e.Title = m.French.Title ?? m.English.Title ?? "Learning path"; e.Slug = m.French.Slug ?? m.English.Slug ?? $"path-{e.Id:N}"; e.Summary = sanitizer.Sanitize(m.French.Summary); e.Status = m.French.PublicationStatus; if (m.Thumbnail is not null) e.Thumbnail = m.Thumbnail; db.Entry(e).Property<bool>("IsDeleted").CurrentValue = false; Upsert(e, "fr", m.French); Upsert(e, "en", m.English); if (m.Id is null || m.Id == Guid.Empty) db.StudyLearningPaths.Add(e); await db.SaveChangesAsync(t); return (true, e.Id, null); }

    private void Upsert(LearningPath e, string l, AdminLearningPathTranslationDto i)
    { if (string.IsNullOrWhiteSpace(i.Title) && string.IsNullOrWhiteSpace(i.Slug)) return; var x = e.Translations.FirstOrDefault(x => x.LanguageCode == l); if (x is null) { x = new LearningPathTranslation { Id = Guid.NewGuid(), LearningPathId = e.Id }; e.Translations.Add(x); } x.LanguageCode = l; x.Title = i.Title?.Trim() ?? ""; x.Slug = i.Slug?.Trim() ?? ""; x.Summary = sanitizer.Sanitize(i.Summary); x.MetaTitle = i.MetaTitle; x.MetaDescription = i.MetaDescription; x.PublicationStatus = i.PublicationStatus; }
}