using Microsoft.EntityFrameworkCore;
using OumezzineAcademy.Application.Abstractions;
using OumezzineAcademy.Domain.Catalog;
using OumezzineAcademy.Infrastructure.Data;

namespace OumezzineAcademy.Infrastructure.Persistence;

public sealed class EfAdminQuestionQueries(ApplicationDbContext db) : IAdminQuestionQueries
{
    public async Task<AdminQuestionQuizContextDto?> ListAsync(Guid courseId, Guid chapterId, Guid quizId, CancellationToken t = default)
    { var q = await db.StudyCourseQuizzes.AsNoTracking().Where(x => x.Id == quizId && x.CourseContentId == chapterId && x.CourseContent.CourseId == courseId).Select(x => new AdminQuestionQuizContextDto(courseId, chapterId, quizId, x.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.Title, x.CourseContent.Course.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.CourseContent.Course.Title, x.CourseContent.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.CourseContent.Title, x.Translations.Where(t => t.LanguageCode == "fr").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), x.Translations.Where(t => t.LanguageCode == "en").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), new List<AdminQuestionListItemDto>())).FirstOrDefaultAsync(t); if (q is null) return null; var items = await db.StudyQuizQuestions.AsNoTracking().Where(x => x.CourseQuizId == quizId).OrderBy(x => x.Order).ThenBy(x => x.Id).Select(x => new AdminQuestionListItemDto(x.Id, x.Order, x.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Text).FirstOrDefault() ?? x.Text, x.Translations.Where(t => t.LanguageCode == "fr").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), x.Translations.Where(t => t.LanguageCode == "en").Select(t => (StudyStatus?)t.PublicationStatus).FirstOrDefault(), x.Answers.Count, x.Answers.Any(a => a.IsCorrect))).ToListAsync(t); return q with { Questions = items }; }

    public async Task<AdminQuestionEditDto?> GetFormAsync(Guid courseId, Guid chapterId, Guid quizId, Guid? questionId, CancellationToken token = default)
    { var quiz = await db.StudyCourseQuizzes.AsNoTracking().Where(x => x.Id == quizId && x.CourseContentId == chapterId && x.CourseContent.CourseId == courseId).Select(x => new { CourseTitle = x.CourseContent.Course.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.CourseContent.Course.Title, ChapterTitle = x.CourseContent.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.CourseContent.Title, QuizTitle = x.Translations.Where(t => t.LanguageCode == "fr").Select(t => t.Title).FirstOrDefault() ?? x.Title }).FirstOrDefaultAsync(token); if (quiz is null) return null; var q = questionId.HasValue ? await db.StudyQuizQuestions.AsNoTracking().Include(x => x.Translations).Include(x => x.Answers).ThenInclude(x => x.Translations).FirstOrDefaultAsync(x => x.Id == questionId && x.CourseQuizId == quizId, token) : null; return new AdminQuestionEditDto(q?.Id ?? Guid.Empty, courseId, chapterId, quizId, q?.Order ?? (await db.StudyQuizQuestions.CountAsync(x => x.CourseQuizId == quizId, token) + 1), quiz.CourseTitle, quiz.ChapterTitle, quiz.QuizTitle, q?.Translations.FirstOrDefault(x => x.LanguageCode == "fr")?.Text, q?.Translations.FirstOrDefault(x => x.LanguageCode == "fr")?.PublicationStatus ?? StudyStatus.Draft, q?.Translations.FirstOrDefault(x => x.LanguageCode == "en")?.Text, q?.Translations.FirstOrDefault(x => x.LanguageCode == "en")?.PublicationStatus ?? StudyStatus.Draft, q?.Answers.OrderBy(x => x.CreatedOnUtc).Select(x => new AdminAnswerDto(x.Id, x.Translations.FirstOrDefault(t => t.LanguageCode == "fr")?.Text, x.Translations.FirstOrDefault(t => t.LanguageCode == "en")?.Text, x.IsCorrect)).ToList() ?? new List<AdminAnswerDto>()); }
}